=== alejandrovap/DTD/cinema.dtd
<!ELEMENT cinema (film+, filmmaker+, note)>
<!ELEMENT film (name)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST film id ID #REQUIRED>
<!ATTLIST film maker IDREF #IMPLIED>
<!ELEMENT filmmaker (name+)>
<!ATTLIST filmmaker id ID #REQUIRED>
<!ELEMENT note (#PCDATA|alert)*>
<!ELEMENT alert EMPTY>

=== alejandrovap/DTD/cinema.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE cinema SYSTEM "cinema.dtd">
<cinema>
    <film id="F1" maker="M1">
        <name>The Silence of the Lambs</name>
    </film>
    <film id="F2" maker="M2">
        <name>2 Fast 2 Furious</name>
    </film>
    <film id="F3" maker="M3">
        <name>Shrek</name>
    </film>
    <filmmaker id="M1">
        <name>Jonathan Demme</name>
    </filmmaker>
    <filmmaker id="M2">
        <name>Rob Cohen</name>
    </filmmaker>
    <filmmaker id="M3">
        <name>Andrew Adamson</name>
        <name>Vicky Jenson</name>
    </filmmaker>
    <note>
        This is important
        <alert/>
    </note>
</cinema>
